### ISSUE TITLE
naked-mole rat protein file is broken

### ISSUE THREAD

**Issue by antonkulaga** [maglab/naked-mole-rat-portal#1]
In the proteins.fa http://alfred.liv.ac.uk/downloads/naked_mole_rat/naked_mole_rat_proteins.zip
at line 167563 you have the following phrase: 
```
Resource temporarily unavailable (4).
```
I had to remove it manually for homology analysis as it crashed diamond software

**Comment by antonkulaga** [comment]
After deleting the line manually everything worked well ( https://github.com/bbuchfink/diamond/issues/179#issuecomment-350549428 ), please update the file on the website

**Comment by zfarooq2** [comment]
Thanks @antonkulaga, its been updated
